# Generated by Django 4.2.19 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('นักศึกษาทุนผู้ยืม', 'นักศึกษาทุนผู้ยืม'), ('นักศึกษาทั่วไป', 'นักศึกษาทั่วไป')], max_length=50)),
                ('term', models.CharField(choices=[('1/2567', '1/2567'), ('2/2567', '2/2567')], max_length=10)),
                ('activity_type', models.CharField(choices=[('กิจกรรมพัฒนาชุมชน', 'กิจกรรมพัฒนาชุมชน / ศาสนสถานต่างๆ'), ('กิจกรรมในคณะ', 'กิจกรรมในคณะ / มหาวิทยาลัย')], max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('hours', models.FloatField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
